### ISSUE TITLE
About the results in the code

### ISSUE THREAD

**Issue by ark1234** [Jiang-HB/DiffusionReg#2]
Thank you so much for your excellent work and the code.

I tried to train by myself with the results of those in test.py:
AUC_R: 0.725, 0.913, 0.970 | AUC_t: 0.895, 0.937, 0.958 |

And the pre-trained models provided by you in test.py:
AUC_R: 0.708, 0.902, 0.958 | AUC_t: 0.880, 0.925, 0.948 |  

It didn't fit with the paper's results.

I don't know the meaning of those numbers. Please explain to me when you have time.

Thanks a lot!

**Comment by Jiang-HB** [comment]
Hi,

Sorry for the delayed response, and thank you very much for pointing out these issues.

Regarding the criteria, I have renamed them in the code to maintain consistency with the paper (AUC -> mAP). Please check.

Additionally, due to potential code reorganization, especially in data processing, the results in this version show higher precisions than those in our original paper. I will promptly review them and get back to you asap.

Best wishes,
Haobo

**Comment by ark1234** [comment]
Thank you very much for your reply and update of the code!

It helps me a lot!

By the way, could I have a copy of the Appendix pdf also?

Here is my email:flin2@wpi.edu

Thank you very much!

**Comment by Jiang-HB** [comment]
Hi,


You can download the appendix on the openreview.


Best,
Haobo&nbsp;

--------------原始邮件--------------
发件人："Ark&nbsp;Lin ***@***.***&gt;;
发送时间：2024年1月3日(星期三) 凌晨5:04
收件人："Jiang-HB/DiffusionReg" ***@***.***&gt;;
抄送："蒋豪博 ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [Jiang-HB/DiffusionReg] About the results in the code (Issue #2)
-----------------------------------

 

 
Thank you very much for your reply and update of the code!
 
It helps me a lot!
 
By the way, could I have a copy of the Appendix pdf also?
 
Here is my ***@***.***
 
Thank you very much!
